

version: "3.9"

services:
  frontend:
    image: shaith/online-education-frontend:latest
    ports:
      - "3000:80"
    networks:
      - app-network
    restart: always

  backend:
    image: shaith/online-education-backend:latest
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://online-education-mysql.ccju26ue634z.us-east-1.rds.amazonaws.com:3306/users?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: YourSecurePassword123!
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-network
    restart: always

volumes:
  frontend_data:
  backend_data:

networks:
  app-network:
    driver: bridge
